//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstEmployeeTask
{
    using System;
    
    public enum AuthStatus : byte
    {
        Invalid = 0,
        Authenticated = 1,
        UnAuthenticated = 2
    }
}
