//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstEmployeeTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int Id { get; set; }
        public string Password { get; set; }
        public Nullable<AuthStatus> AuthStatus { get; set; }


        public override string ToString()
        {
            return $"Name: {Name} Email: {Email} Password: {Password} Mobile: {Mobile} AuthStatus: {AuthStatus}";
        }
    }
}
